server:
  port: 80

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eventgo
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      dialect:
        MySQLDialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret:
    access: &E)H@McQfTjWnZr4u7x!A%D*G-JaNdRg
    refresh: gVkYp3s6v9y$B&E)H+MbQeThWmZq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G